version: "2.4"
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ
      - "discovery.type=single-node"
  logstash:
    restart: always
    image: docker.elastic.co/logstash/logstash:7.17.8
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 515:515
    environment:
      - TZ
  grafana:
    restart: always
    image: grafana/grafana-oss:9.3.2
    ports:
      - 3000:3000
    environment:
      - TZ
